// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-mFzsHov9_ZzUXcFVc0btidyux4Iuy8',
    appId: '1:973096622185:web:39c1f69409b3e29e6a6af8',
    messagingSenderId: '973096622185',
    projectId: 'cloudstash-c',
    authDomain: 'cloudstash-c.firebaseapp.com',
    storageBucket: 'cloudstash-c.firebasestorage.app',
    measurementId: 'G-SXMB925TJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2goGmm9pO8cWLQD2FPm15L8vITJ_TNM',
    appId: '1:973096622185:android:c4c1e246359c66c56a6af8',
    messagingSenderId: '973096622185',
    projectId: 'cloudstash-c',
    storageBucket: 'cloudstash-c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArdRoL1ASbr56yUIWW7tAFv0moA2jZVjM',
    appId: '1:973096622185:ios:d787d0ad4f594ce06a6af8',
    messagingSenderId: '973096622185',
    projectId: 'cloudstash-c',
    storageBucket: 'cloudstash-c.firebasestorage.app',
    iosBundleId: 'com.vivekupasani.docs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArdRoL1ASbr56yUIWW7tAFv0moA2jZVjM',
    appId: '1:973096622185:ios:d787d0ad4f594ce06a6af8',
    messagingSenderId: '973096622185',
    projectId: 'cloudstash-c',
    storageBucket: 'cloudstash-c.firebasestorage.app',
    iosBundleId: 'com.vivekupasani.docs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc-mFzsHov9_ZzUXcFVc0btidyux4Iuy8',
    appId: '1:973096622185:web:fc56282436ff4d3d6a6af8',
    messagingSenderId: '973096622185',
    projectId: 'cloudstash-c',
    authDomain: 'cloudstash-c.firebaseapp.com',
    storageBucket: 'cloudstash-c.firebasestorage.app',
    measurementId: 'G-BKCTQFYCV6',
  );
}
