// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FL_DvqO6hdy67ZsOIAAIeF_PuWu3BJA',
    appId: '1:616044693358:web:1676bf2768cf1b0c64e37f',
    messagingSenderId: '616044693358',
    projectId: 'single-5664b',
    authDomain: 'single-5664b.firebaseapp.com',
    databaseURL: 'https://single-5664b-default-rtdb.firebaseio.com',
    storageBucket: 'single-5664b.appspot.com',
    measurementId: 'G-JQWW8GHMFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFaoTLK6EJQUKqJiB3xe2jrF07IFGTtFk',
    appId: '1:616044693358:android:0c60b085801931a364e37f',
    messagingSenderId: '616044693358',
    projectId: 'single-5664b',
    databaseURL: 'https://single-5664b-default-rtdb.firebaseio.com',
    storageBucket: 'single-5664b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPQjBMMLv4kqUgRec9-0odMGqfahI514',
    appId: '1:616044693358:ios:1df3b2a3ac9a6cce64e37f',
    messagingSenderId: '616044693358',
    projectId: 'single-5664b',
    databaseURL: 'https://single-5664b-default-rtdb.firebaseio.com',
    storageBucket: 'single-5664b.appspot.com',
    iosBundleId: 'com.vivekupasani.cloudstash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPQjBMMLv4kqUgRec9-0odMGqfahI514',
    appId: '1:616044693358:ios:1df3b2a3ac9a6cce64e37f',
    messagingSenderId: '616044693358',
    projectId: 'single-5664b',
    databaseURL: 'https://single-5664b-default-rtdb.firebaseio.com',
    storageBucket: 'single-5664b.appspot.com',
    iosBundleId: 'com.vivekupasani.cloudstash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4FL_DvqO6hdy67ZsOIAAIeF_PuWu3BJA',
    appId: '1:616044693358:web:511091ee83f2c41764e37f',
    messagingSenderId: '616044693358',
    projectId: 'single-5664b',
    authDomain: 'single-5664b.firebaseapp.com',
    databaseURL: 'https://single-5664b-default-rtdb.firebaseio.com',
    storageBucket: 'single-5664b.appspot.com',
    measurementId: 'G-7WKDCK5TZY',
  );
}
